### ISSUE TITLE
Erro ao ler dados de 2019

### ISSUE THREAD

**Issue by erclsb** [dados-covid/srag#1]
Um erro é obtido ao tentar ler os dados de 2019 no script update_srag_database.py. A seguinte mensagem de erro é mostrada.

```
Csv file found at <https://opendatasus.saude.gov.br/dataset/bd-srag-2019>

Downloading from <https://opendatasus.saude.gov.br/dataset/e99cfd21-3d8c-4ff9-bd9c-04b8b2518739/resource/9d1165b3-80a3-4ec4-a6ad-e980e3d354b2/download/influd19_limpo-27.04.2020-final.csv> ...

 Problema com leitura do arquivo. Não identifiquei qual.
Traceback (most recent call last):
  File "update_srag_database.py", line 21, in <module>
    df = get_srag_data(years=[year],update=False,treat=True,save_local=False)
  File "D:\Erico\Documents\git\victor\srag\_notebooks\srag_functions.py", line 48, in get_srag_data
    df = pd.read_csv(url,sep=sep,quotechar=quotechar,dtype=object)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas\_libs\parsers.pyx", line 518, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 620, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 25044: invalid start byte
```

**Comment by erclsb** [comment]
A leitura dos dados de 2019 está comentada por enquanto, são lidos apenas os dados de 2020 e 2021.

**Comment by victor-marchesini** [comment]
o fechamento não é automático como no GitLab...
